name: Update shows

on:
  schedule:
    - cron: "0 6 * * *"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-shows:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Save previous JSON
        run: cp shows.json prev_shows.json

      - name: Update shows
        run: python update_shows.py

      - name: Compare JSON files
        id: compare
        run: |
          if cmp -s prev_shows.json shows.json; then
            echo "changed=false" >> "$GITHUB_OUTPUT"
            echo "No changes detected."
          else
            echo "changed=true" >> "$GITHUB_OUTPUT"
            echo "Changes detected."
          fi

      - name: Commit and push changes
        if: steps.compare.outputs.changed == 'true'
        run: |
          rm prev_shows.json

          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add shows.json
          git commit -m "🤖 Update shows"
          git push

